/**
 * On-site listing detail helpers.
 *
 * lib/listings.ts and lib/sold-listings.ts are auto-generated by Compass sync
 * scripts, so the derived slug logic lives here (a hand-maintained sibling) to
 * survive regeneration. This module is the SINGLE source of truth for a
 * listing's on-site URL slug — app/listings/[slug]/page.tsx
 * (generateStaticParams + lookup), components/ListingCard.tsx, lib/hero-slides.ts,
 * and lib/site-urls.ts all call resolveListingDetailSlug() / listingSlug(), so
 * the generated routes and the links pointing at them can never drift apart.
 *
 * Active and sold inventory share the /listings/[slug] namespace. Active
 * listings always claim their address-derived slug; a sold home that would
 * collide is assigned a deterministic `-sold` (then `-sold-{token}`) suffix.
 * Callers must use resolveListingDetailSlug() for hrefs — never assume the
 * address slug is the page slug.
 */
import { listings, type Listing } from './listings'
import { soldListings } from './sold-listings'

export type ListingRef = Pick<Listing, 'address' | 'city'> &
  Partial<Pick<Listing, 'status' | 'compassUrl'>>

/**
 * Stable address-derived slug (identity), NOT necessarily the URL slug.
 *
 *   { address: "1901 New Bristol Ln", city: "Brentwood, TN 37027 | MLS #3245826" }
 *   → "1901-new-bristol-ln-brentwood"
 *
 * Lot/unit prefixes in `city` ("Lot 54, Brentwood…") stay in the slug so two
 * homes on the same street remain distinct. Use resolveListingDetailSlug()
 * when you need the on-site path.
 */
export function listingSlug(listing: Pick<Listing, 'address' | 'city'>): string {
  // `city` can look like "Brentwood, TN 37027 | MLS #3245826" — keep only the
  // first comma-separated token for a compact, stable identity slug.
  const locality = listing.city.split('|')[0].split(',')[0]
  return `${listing.address} ${locality}`
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

export function isSoldStatus(status: string): boolean {
  const s = status.toLowerCase()
  return s.includes('sold') || s.includes('closed')
}

/**
 * A sold record is indexable only when it has an address, a real locality, a
 * positive price, and at least one physical spec. Thin Compass cards (price
 * only, undisclosed address, city of just "TN") do not get a public page —
 * ListingCard keeps the Compass source link instead of indexing an empty URL.
 */
export function isIndexableSoldListing(listing: Listing): boolean {
  const city = listing.city.trim()
  const hasLocality = city.length > 0 && city.toUpperCase() !== 'TN'
  const hasSpec =
    listing.beds !== undefined ||
    listing.baths !== undefined ||
    listing.sqft !== undefined ||
    listing.acres !== undefined
  return Boolean(
    listing.address &&
      listing.address !== 'Undisclosed Address' &&
      hasLocality &&
      listing.price > 0 &&
      hasSpec,
  )
}

function listingIdentity(listing: Pick<Listing, 'address' | 'city'> & Partial<Pick<Listing, 'compassUrl'>>): string {
  return listing.compassUrl || `${listing.address}\n${listing.city}`
}

/** Stable extra suffix when `-sold` itself collides. */
export function soldDisambiguationToken(listing: Pick<Listing, 'compassUrl'>): string {
  const lid = listing.compassUrl.match(/(\d+)_lid/)?.[1]
  if (lid) return lid.slice(-10)
  const pid = listing.compassUrl.match(/\/([A-Za-z0-9]+)_pid/)?.[1]
  if (pid) return pid.toLowerCase()
  return listing.compassUrl.replace(/[^a-z0-9]+/gi, '').slice(-10).toLowerCase() || 'x'
}

/**
 * Assign URL slugs for a pool of active + sold listings.
 * Active homes always win the address-derived slug. Sold homes that collide
 * take `{slug}-sold`, then `{slug}-sold-{token}` if that is also taken.
 * Thin sold records are omitted (no page).
 */
export function assignListingDetailSlugs(
  activeListings: readonly Listing[],
  sold: readonly Listing[],
): Map<string, Listing> {
  const slugToListing = new Map<string, Listing>()

  for (const listing of activeListings) {
    const slug = listingSlug(listing)
    if (!slugToListing.has(slug)) {
      slugToListing.set(slug, listing)
    }
  }

  for (const listing of sold) {
    if (!isIndexableSoldListing(listing)) continue
    let slug = listingSlug(listing)
    if (slugToListing.has(slug)) {
      slug = `${slug}-sold`
    }
    if (slugToListing.has(slug)) {
      slug = `${listingSlug(listing)}-sold-${soldDisambiguationToken(listing)}`
    }
    slugToListing.set(slug, listing)
  }

  return slugToListing
}

function buildIdentityIndex(slugToListing: Map<string, Listing>): Map<string, string> {
  const identityToSlug = new Map<string, string>()
  for (const [slug, listing] of slugToListing) {
    identityToSlug.set(listingIdentity(listing), slug)
  }
  return identityToSlug
}

const detailBySlug = assignListingDetailSlugs(listings, soldListings)
const detailSlugByIdentity = buildIdentityIndex(detailBySlug)

/** Slugs of every active listing that has a generated on-site detail page. */
export const activeListingSlugs: ReadonlySet<string> = new Set(
  listings.map((l) => listingSlug(l)),
)

/** Slugs of every generated on-site detail page (active + indexable sold). */
export const listingDetailSlugs: ReadonlySet<string> = new Set(detailBySlug.keys())

export function getListingBySlug(slug: string): Listing | undefined {
  return detailBySlug.get(slug)
}

/**
 * URL slug for this listing's on-site page, or undefined when none exists.
 *
 * Resolution order:
 *   1. Exact Compass URL identity (unique across active + sold).
 *   2. Among listings that share the address slug: honor an explicit Sold
 *      status (hero slides use "Recently Sold"); otherwise prefer the active
 *      listing so a live home never silently resolves to a past sale.
 *   3. Address-only refs with a single match use that page.
 */
export function resolveListingDetailSlug(listing: ListingRef): string | undefined {
  if (listing.compassUrl) {
    const byId = detailSlugByIdentity.get(listing.compassUrl)
    if (byId) return byId
  }

  const base = listingSlug(listing)
  const candidates = [...detailBySlug.entries()].filter(([, l]) => listingSlug(l) === base)
  if (candidates.length === 0) return undefined

  if (listing.status && isSoldStatus(listing.status)) {
    const sold = candidates.find(([, l]) => isSoldStatus(l.status))
    if (sold) return sold[0]
  }
  if (listing.status && !isSoldStatus(listing.status)) {
    const active = candidates.find(([, l]) => !isSoldStatus(l.status))
    if (active) return active[0]
  }

  const active = candidates.find(([, l]) => !isSoldStatus(l.status))
  if (active) return active[0]
  return candidates[0][0]
}

export function listingDetailPath(listing: ListingRef): string | null {
  const slug = resolveListingDetailSlug(listing)
  return slug ? `/listings/${slug}` : null
}

const SITE = 'https://www.joshuafink.com'

export function listingCanonicalUrl(listing: ListingRef): string {
  const path = listingDetailPath(listing)
  if (path) return `${SITE}${path}`
  return listing.compassUrl || `${SITE}/listings`
}

/**
 * Whether an on-site /listings/[slug] detail page exists for this listing.
 * True for active inventory and for indexable sold records.
 */
export function hasListingDetail(listing: ListingRef): boolean {
  return resolveListingDetailSlug(listing) !== undefined
}

/**
 * Hand-maintained map of listing slug → YouTube video ID for virtual-tour
 * walkthroughs on the Joshua Fink Group channel
 * (youtube.com/channel/UCc6j1NWgJeb00pT5xsenz3g). Lives here rather than in
 * lib/listings.ts so the Compass re-sync that regenerates that file can't
 * wipe it. After uploading a tour, add a line like:
 *   '1901-new-bristol-ln-brentwood': 'dQw4w9WgXcQ',
 * and the listing page embeds the player + emits VideoObject schema.
 * Entries for slugs no longer active are simply never rendered.
 */
export const tourVideos: Record<string, string> = {}

/** YouTube video ID of a listing's virtual tour, if one has been uploaded. */
export function getTourVideoId(slug: string): string | undefined {
  return tourVideos[slug]
}
