/**
 * On-site listing detail helpers.
 *
 * lib/listings.ts is auto-generated by scripts/fetch-images.mjs and rewritten on
 * every Compass sync, so the derived slug logic lives here (a hand-maintained
 * sibling) to survive regeneration. This module is the SINGLE source of truth
 * for a listing's on-site URL slug — app/listings/[slug]/page.tsx
 * (generateStaticParams + lookup) and components/ListingCard.tsx both call
 * listingSlug(), so the generated routes and the links pointing at them can
 * never drift apart.
 */
import { listings, type Listing } from './listings'

/**
 * Stable URL slug for a listing's on-site detail page, derived from the street
 * address + city locality.
 *
 *   { address: "1901 New Bristol Ln", city: "Brentwood, TN 37027 | MLS #3245826" }
 *   → "1901-new-bristol-ln-brentwood"
 */
export function listingSlug(listing: Pick<Listing, 'address' | 'city'>): string {
  // `city` can look like "Brentwood, TN 37027 | MLS #3245826" — keep only the
  // locality (the part before the first comma / MLS suffix) for a clean slug.
  const locality = listing.city.split('|')[0].split(',')[0]
  return `${listing.address} ${locality}`
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

/** Slugs of every active listing that has a generated on-site detail page. */
export const activeListingSlugs: ReadonlySet<string> = new Set(
  listings.map((l) => listingSlug(l)),
)

/**
 * Whether an on-site /listings/[slug] detail page exists for this listing.
 * Only active `listings` get detail pages — sold homes (rendered by the same
 * ListingCard) return false so their card keeps linking straight to Compass
 * instead of to a slug that was never statically generated.
 */
export function hasListingDetail(listing: Pick<Listing, 'address' | 'city'>): boolean {
  return activeListingSlugs.has(listingSlug(listing))
}

/** Resolve a slug back to its active listing (undefined for unknown slugs). */
export function getListingBySlug(slug: string): Listing | undefined {
  return listings.find((l) => listingSlug(l) === slug)
}
